apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-mif
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-mif
  template:
    metadata:
      labels:
        app: devops-mif
    spec:
      containers:
      - name: devops-mif
        image: thehorseman/devops-mif_images:testing
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: devops-mif
spec:
  type: ClusterIP
  selector:
    app: devops-mif
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80