image: thehorseman/devops-mif_images:testing

services:
  - docker:dind

before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

build-and-push:
  stage: build
  script:
    - docker build -t thehorseman/devops-mif_images:testing .
    - docker push thehorseman/devops-mif_images:testing
  only:
    - main