apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: yourusername/yourphpapp:tag
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: php-app-service
spec:
  type: LoadBalancer
  selector:
    app: php-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80