version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:80"
    volumes:
      - ./index.php:/var/www/html/index.php
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  default:
    driver: bridge
